# -*- coding: utf-8 -*-

__author__ = 'mayns'


class Scientist(object):

    json_data = {
        0: dict(
            email=u'oks',
            password=u'qwe'
        ),

        1: dict(
            email=u'oksgorobets@gmail.com',
            password=u'alice',
            first_name=u'Оксана',
            last_name=u'Горобец',
            middle_name=u'Валерьевна',
            dob=u'13.10.1986',
            gender=u'f',
            image=u'http://www.gravatar.com/avatar/0feef2db09551df83e7bf61d2d1de25e.png',
            location_country=u'Russia',
            location_city=u'Moscow',
            middle_education=[
                dict(
                    country=u'Россия',
                    city=u'Тверь',
                    school=u'Гимназия 8',
                    finish_year=u'2004'
                )
            ],
            high_education=[
                dict(
                    country=u'Россия',
                    city=u'Тверь',
                    university=u'ТвГУ',
                    faculty=u'Филологический',
                    chair=u'Издательское дело и редактирование',
                    degree=u'специалист',
                    finish_year=u'2011'
                ),
                dict(
                    country=u'Россия',
                    city=u'Москва',
                    university=u'МГУ им. Ломоносова',
                    faculty=u'ВМиК',
                    chair=u'',
                    degree=u'bachelor',
                    finish_year=u'2015'
                )
            ],
            publications=[
                dict(
                    title=u'',
                    metadata=u'',
                    link=u''
                )
            ],
            interests=[u'лингвистика', u'искусственный интеллект', u'алгоритмы'],
            about=u'я как то надралась перед конференцией на филфаке. где была одновременно ведущим и докладчиком. '
                  u'а доклад был значит по Лавкрафту… че-то бла-бла, потом грю на нафиг, давайте я вам стихи почитаю)',

            contacts=[
                dict(
                    connection=u'Phone',
                    number=u'89104714456'
                ),
                dict(
                    connection=u'email',
                    number=u'ifine13@gmail.com'
                ),
                dict(
                    connection=u'Skype',
                    number=u'leff_mayns'
                ),
                dict(
                    connection=u'Instagram',
                    number=u'@leff_mayns'
                )
            ],

            project_ids=[],
            desired_projects=[],
            managing_projects=[],

            swear=u'true',
        ),
        2: dict(
            email=u'',
            password=u'',
            first_name=u'',
            last_name=u'',
            middle_name=u'',
            dob=u'',
            gender=u'',
            image=u'',
            location_country=u'',
            location_city=u'',
            middle_education=u'',
            high_education=u'',
            publications=u'',
            interests=u'',
            project_ids=u'',
            about=u'',
            contacts=u'',
            desired_projects=u'',
            managing_projects=u'',
            swear=u'',

        ),
        3: dict(
            email=u'',
            password=u'',
            first_name=u'',
            last_name=u'',
            middle_name=u'',
            dob=u'',
            gender=u'',
            image=u'',
            location_country=u'',
            location_city=u'',
            middle_education=u'',
            high_education=u'',
            publications=u'',
            interests=u'',
            project_ids=u'',
            about=u'',
            contacts=u'',
            desired_projects=u'',
            managing_projects=u'',
            swear=u'',
        ),
        4: dict(
            email=u'',
            password=u'',
            first_name=u'',
            last_name=u'',
            middle_name=u'',
            dob=u'',
            gender=u'',
            image=u'',
            location_country=u'',
            location_city=u'',
            middle_education=u'',
            high_education=u'',
            publications=u'',
            interests=u'',
            project_ids=u'',
            about=u'',
            contacts=u'',
            desired_projects=u'',
            managing_projects=u'',
            swear=u'',
        ),
        5: dict(
            email=u'',
            password=u'',
            first_name=u'',
            last_name=u'',
            middle_name=u'',
            dob=u'',
            gender=u'',
            image=u'',
            location_country=u'',
            location_city=u'',
            middle_education=u'',
            high_education=u'',
            publications=u'',
            interests=u'',
            project_ids=u'',
            about=u'',
            contacts=u'',
            desired_projects=u'',
            managing_projects=u'',
            swear=u'',
        ),
        6: dict(
            email=u'',
            password=u'',
            first_name=u'',
            last_name=u'',
            middle_name=u'',
            dob=u'',
            gender=u'',
            image=u'',
            location_country=u'',
            location_city=u'',
            middle_education=u'',
            high_education=u'',
            publications=u'',
            interests=u'',
            project_ids=u'',
            about=u'',
            contacts=u'',
            desired_projects=u'',
            managing_projects=u'',
            swear=u'',
        ),
        7: dict(
            email=u'',
            password=u'',
            first_name=u'',
            last_name=u'',
            middle_name=u'',
            dob=u'',
            gender=u'',
            image=u'',
            location_country=u'',
            location_city=u'',
            middle_education=u'',
            high_education=u'',
            publications=u'',
            interests=u'',
            project_ids=u'',
            about=u'',
            contacts=u'',
            desired_projects=u'',
            managing_projects=u'',
            swear=u'',
        ),
        8: dict(
            email=u'',
            password=u'',
            first_name=u'',
            last_name=u'',
            middle_name=u'',
            dob=u'',
            gender=u'',
            image=u'',
            location_country=u'',
            location_city=u'',
            middle_education=u'',
            high_education=u'',
            publications=u'',
            interests=u'',
            project_ids=u'',
            about=u'',
            contacts=u'',
            desired_projects=u'',
            managing_projects=u'',
            swear=u'',
        ),
        9: dict(
            email=u'',
            password=u'',
            first_name=u'',
            last_name=u'',
            middle_name=u'',
            dob=u'',
            gender=u'',
            image=u'',
            location_country=u'',
            location_city=u'',
            middle_education=u'',
            high_education=u'',
            publications=u'',
            interests=u'',
            project_ids=u'',
            about=u'',
            contacts=u'',
            desired_projects=u'',
            managing_projects=u'',
            swear=u'',
        ),
        10: dict(
            email=u'',
            password=u'',
            first_name=u'',
            last_name=u'',
            middle_name=u'',
            dob=u'',
            gender=u'',
            image=u'',
            location_country=u'',
            location_city=u'',
            middle_education=u'',
            high_education=u'',
            publications=u'',
            interests=u'',
            project_ids=u'',
            about=u'',
            contacts=u'',
            desired_projects=u'',
            managing_projects=u'',
            swear=u'',
        )
    }

    @classmethod
    def get_data(cls, num=u'1'):
        return cls.json_data.get(num)